=== deathmarine/Luyten/src/theme.dtd
<!-- DTD for RSyntaxTextArea Theme XML. -->
<!ELEMENT RSyntaxTheme (baseFont, background, caret, selection,
      currentLineHighlight, marginLine, markAllHighlight, markOccurrencesHighlight,
      matchedBracket, hyperlinks, secondaryLanguages, gutterBorder, lineNumbers,
      foldIndicator, iconRowHeader, tokenStyles)>
<!ELEMENT background EMPTY>
<!ELEMENT baseFont EMPTY>
<!ELEMENT caret EMPTY>
<!ELEMENT selection EMPTY>
<!ELEMENT currentLineHighlight EMPTY>
<!ELEMENT marginLine EMPTY>
<!ELEMENT markAllHighlight EMPTY>
<!ELEMENT markOccurrencesHighlight EMPTY>
<!ELEMENT matchedBracket EMPTY>
<!ELEMENT hyperlinks EMPTY>
<!ELEMENT secondaryLanguages (language+)>
<!ELEMENT language EMPTY>
<!ELEMENT gutterBorder EMPTY>
<!ELEMENT lineNumbers EMPTY>
<!ELEMENT foldIndicator EMPTY>
<!ELEMENT iconRowHeader EMPTY>
<!ELEMENT tokenStyles (style+)>
<!ELEMENT style EMPTY>

<!ATTLIST RSyntaxTheme
      version  CDATA #REQUIRED>
<!ATTLIST background
      color    CDATA #REQUIRED>
<!ATTLIST baseFont
      family    CDATA #IMPLIED
      size      CDATA #REQUIRED>
<!ATTLIST caret
      color     CDATA #REQUIRED>
<!ATTLIST selection
      bg        CDATA #REQUIRED
      roundedEdges (true|false) "false">
<!ATTLIST currentLineHighlight
      color     CDATA #REQUIRED
      fade      (true|false) "false">
<!ATTLIST marginLine
      fg         CDATA #REQUIRED>
<!ATTLIST markAllHighlight
      color      CDATA #REQUIRED>
<!ATTLIST markOccurrencesHighlight
      color      CDATA #REQUIRED
      border     (true|false) "false">
<!ATTLIST matchedBracket
      fg            CDATA #REQUIRED
      bg            CDATA #IMPLIED
      highlightBoth (true|false) "false"
      animate       (true|false) "false">
<!ATTLIST hyperlinks
      fg         CDATA #REQUIRED>
<!ATTLIST language
      index      (1|2|3) #REQUIRED
      bg         CDATA   #REQUIRED>
<!ATTLIST gutterBorder
      color      CDATA #REQUIRED>
<!ATTLIST lineNumbers
      fg         CDATA #REQUIRED
      fontFamily CDATA #IMPLIED
      fontSize   CDATA #IMPLIED>
<!ATTLIST foldIndicator
      fg         CDATA #REQUIRED
      iconBg     CDATA #REQUIRED>
<!ATTLIST iconRowHeader
      activeLineRange CDATA #REQUIRED>
<!ATTLIST style
      token      CDATA #REQUIRED
      fg         CDATA #IMPLIED
      bg         CDATA #IMPLIED
      fontFamily CDATA #IMPLIED
      fontSize   CDATA #IMPLIED
      bold       (true|false) "false"
      italic     (true|false) "false"
      underline  (true|false) "false">

=== deathmarine/Luyten/src/themes/eclipse.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE RSyntaxTheme SYSTEM "theme.dtd">

<!-- Theme that mimics Eclipse's defaults. -->
<RSyntaxTheme version="1.0">

	<!-- Specify family="..." attribute to override system default monospaced. -->
	<baseFont size="12" />

	<!-- General editor colors. -->
	<background color="ffffff" />
	<caret color="000000" />
	<selection bg="c8c8ff" />
	<currentLineHighlight color="e8f2fe" fade="false" />
	<marginLine fg="b0b4b9" />
	<markAllHighlight color="6b8189" />
	<markOccurrencesHighlight color="d4d4d4"
		border="false" />
	<matchedBracket fg="c0c0c0" highlightBoth="false"
		animate="false" />
	<hyperlinks fg="0000ff" />
	<secondaryLanguages>
		<language index="1" bg="fff0cc" />
		<language index="2" bg="dafeda" />
		<language index="3" bg="ffe0f0" />
	</secondaryLanguages>


	<!-- Gutter styling. -->
	<gutterBorder color="dddddd" />
	<lineNumbers fg="787878" />
	<foldIndicator fg="808080" iconBg="ffffff" />
	<iconRowHeader activeLineRange="3399ff" />

	<!-- Syntax tokens. -->
	<tokenStyles>
		<style token="IDENTIFIER" fg="000000" />
		<style token="RESERVED_WORD" fg="7f0055" bold="true" />
		<style token="RESERVED_WORD_2" fg="7f0055" bold="true" />
		<style token="ANNOTATION" fg="808080" />
		<style token="COMMENT_DOCUMENTATION" fg="3f5fbf" />
		<style token="COMMENT_EOL" fg="3f7f5f" />
		<style token="COMMENT_MULTILINE" fg="3f7f5f" />
		<style token="COMMENT_KEYWORD" fg="7F9FBF" bold="true" />
		<style token="COMMENT_MARKUP" fg="7f7f9f" />
		<style token="DATA_TYPE" fg="7f0055" bold="true" />
		<style token="FUNCTION" fg="000000" />
		<style token="LITERAL_BOOLEAN" fg="7f0055" bold="true" />
		<style token="LITERAL_NUMBER_DECIMAL_INT" fg="000000" />
		<style token="LITERAL_NUMBER_FLOAT" fg="000000" />
		<style token="LITERAL_NUMBER_HEXADECIMAL" fg="000000" />
		<style token="LITERAL_STRING_DOUBLE_QUOTE" fg="2900ff" />
		<style token="LITERAL_CHAR" fg="2900ff" />
		<style token="LITERAL_BACKQUOTE" fg="2900ff" />
		<style token="MARKUP_TAG_DELIMITER" fg="808080" />
		<style token="MARKUP_TAG_NAME" fg="3f7f7f" />
		<style token="MARKUP_TAG_ATTRIBUTE" fg="7f7f7f" />
		<style token="MARKUP_TAG_ATTRIBUTE_VALUE" fg="2900ff" />
		<style token="MARKUP_PROCESSING_INSTRUCTION" fg="808080" />
		<style token="MARKUP_CDATA" fg="cc6600" />
		<style token="OPERATOR" fg="000000" />
		<style token="PREPROCESSOR" fg="808080" />
		<style token="REGEX" fg="008040" />
		<style token="SEPARATOR" fg="000000" />
		<style token="VARIABLE" fg="ff9900" bold="true" />
		<style token="WHITESPACE" fg="000000" />

		<style token="ERROR_IDENTIFIER" fg="000000" bg="ffcccc" />
		<style token="ERROR_NUMBER_FORMAT" fg="000000" bg="ffcccc" />
		<style token="ERROR_STRING_DOUBLE" fg="000000" bg="ffcccc" />
		<style token="ERROR_CHAR" fg="000000" bg="ffcccc" />
	</tokenStyles>

</RSyntaxTheme>
